name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: |
           sudo modprobe nbd; sudo modprobe nvme; sudo modprobe nvmet; sudo modprobe xfs
           echo 1024 | sudo tee /sys/kernel/mm/hugepages/hugepages-2048kB/nr_hugepages 1>/dev/null
           cat /sys/kernel/mm/hugepages/hugepages-2048kB/nr_hugepages
           docker run --privileged -v /dev:/dev:rw -v /dev/shm:/dev/shm:rw -v /dev/hugepages:/dev/hugepages:rw --network host --rm hello-world
           for d in */; do
            pushd "$d"
            cargo build --verbose
            popd
           done
    - name: Run tests
      run: |
           for d in */; do
            pushd "$d"
            cargo test --verbose
            popd
           done
