name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: |
           docker run --privileged --rm hello-world
           for d in */; do
            pushd "$d"
            cargo build --verbose
            popd
           done
    - name: Run tests
      run: |
           for d in */; do
            pushd "$d"
            cargo test --verbose
            popd
           done
